# Generated by Django 4.0.5 on 2022-07-01 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('address', models.CharField(max_length=400, verbose_name='Адрес')),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client', to_field='name', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'unique_together': {('name', 'client_name')},
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер')),
                ('sum', models.FloatField(verbose_name='Сумма')),
                ('date', models.DateField(verbose_name='Дата')),
                ('service', models.CharField(max_length=400, verbose_name='Услуга')),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client', to_field='name', verbose_name='Клиент')),
                ('client_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organization', to_field='name', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'Счета',
                'unique_together': {('number', 'client_org')},
            },
        ),
    ]
