# Generated by Django 4.0.5 on 2022-07-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='fraud_score',
            field=models.FloatField(default=0, verbose_name='Оценка мошенничества'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='service_class',
            field=models.IntegerField(default=0, verbose_name='Номер класса услуги'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='service_name',
            field=models.CharField(default='0', max_length=200, verbose_name='Название класса услуги'),
            preserve_default=False,
        ),
    ]
