# Generated by Django 4.0.5 on 2022-07-01 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bill_fraud_score_bill_service_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='fraud_weight',
            field=models.IntegerField(default=0, verbose_name='Оценка мошенничества'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='client_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='api.client', to_field='name', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='client_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='api.client', to_field='name', verbose_name='Клиент'),
        ),
    ]
