# Generated by Django 4.0.5 on 2022-07-08 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_organization_fraud_weight_alter_bill_client_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='client_org',
            new_name='organization',
        ),
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together={('number', 'organization')},
        ),
        migrations.CreateModel(
            name='ColumnNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name_column', models.CharField(max_length=200, verbose_name='Название колонки клиента')),
                ('organization_column', models.CharField(max_length=200, verbose_name='Название колонки организации')),
                ('number_column', models.CharField(max_length=200, verbose_name='Название колонки номера счета')),
                ('sum_column', models.CharField(max_length=200, verbose_name='Название колонки суммы')),
                ('date_column', models.CharField(max_length=200, verbose_name='Название колонки даты')),
                ('service_column', models.CharField(max_length=200, verbose_name='Название колонки услуги')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Название колонок',
                'verbose_name_plural': 'Названия колонок',
            },
        ),
    ]
